// User-facing changelog. Each release lists its changes, one short sentence per
// point so anyone can understand what changed. Newest release first.
export const CHANGELOG = [
  {
    version: '7.1.2',
    date: '2026-07-18',
    notes: [
      'The offline bar now appears briefly and slides away instead of lingering on every screen (including Settings and Login). Connection-only features stay greyed out until you’re back — tap one and the reminder pops up again.',
    ],
  },
  {
    version: '7.1.1',
    date: '2026-07-18',
    notes: [
      'Fixed offline awareness not working on the phone: the offline bar and the greyed-out connection-only features now trigger reliably on Android, not just in a browser.',
      'The “Best” streak badge on Analytics is now easy to read in light mode.',
    ],
  },
  {
    version: '7.1.0',
    date: '2026-07-18',
    notes: [
      'The app now knows when you go offline: a red bar appears and features that need a connection (Dictionary, AI Coach, practice, Friends compare) grey out, then a green “You’re back online” bar confirms when it returns.',
      'When a friend gifts you a streak freeze, you now get a full-screen moment — gifts raining down around a snowflake — and you’ll see it on your next open even if a gift arrived while the app was closed.',
      'Reworked the streak and level-up celebrations: the flame now ignites and flickers, the rays sweep outward, and the level-up arrow rises into place.',
      'The tour’s practice slide now demonstrates all four exercises in turn — a card flips, a pair matches, a blank fills, a synonym flips to its antonym — and the AI Coach slide has a livelier animation.',
      'Book cards in your Library now show both a blue Progress bar and a gold Mastery bar, matching the pack cards inside.',
      'Redesigned the streak card on Analytics with a bigger flame that lights up once you’ve hit today’s goal, and a “Best” badge for your longest streak.',
      'The reminder time picker wheels now scroll endlessly, so you can spin past 12 or 59 without hitting a wall.',
      'Fixed account deletion, which was failing with an unhelpful error.',
    ],
  },
  {
    version: '7.0.0',
    date: '2026-07-18',
    notes: [
      'Progress and mastery are now two separate bars: a blue Progress bar fills as you review and answer correctly, while a gold Mastery bar only grows as words survive the spaced-review ladder — so finishing a pack no longer “masters” it on its own.',
      'Flashcards are pure review now — no right or wrong. Flip through at your own pace and finish with a simple “you reviewed N words”. They still earn XP toward your goal, and no longer skew your accuracy.',
      'Matching, Fill-in-the-blanks and Synonym/Antonym now show a stopwatch that runs while you practise, save your best time per pack, and warn you before you leave and lose a session.',
      'Rebuilt the weekly XP chart as a Sunday-to-Saturday line with a point for each day and a real number axis — and did the same on Compare, now a per-week race showing each of you your total XP for the week.',
      'Streak freezes now sit in a labelled box so it’s clear how many you have, and your level uses a new level-up badge.',
      'Added a level-up celebration when your XP crosses into a new level.',
      'The streak celebration no longer prints the number inside the flame — just the flame and your streak below it.',
      'Revise now stands out with its own green card, distinct from the word packs.',
      'The practice-reminder time picker is a proper scrolling wheel for the hour, minute and AM/PM.',
    ],
  },
  {
    version: '6.1.0',
    date: '2026-07-18',
    notes: [
      'Streak freezes now show as two snowflake pips above your streak — blue when a freeze is ready, muted once one has been spent — and your streak flame is now warm amber.',
      'You can gift a streak freeze to a friend to protect their streak. The gift appears on their friend row and Compare screen whenever they have room, and you can send one to each friend every two weeks.',
      'Get a heads-up the moment a friend gives you a streak freeze.',
      'Fixed the practice-reminder switch turning itself back off: it now stays where you set it, and reminders schedule reliably on newer Android versions.',
    ],
  },
  {
    version: '6.0.0',
    date: '2026-07-18',
    notes: [
      'Added XP: every answer now earns points — 5 for a correct matching, fill-in-the-blank or synonym answer, 2 for a flashcard you knew, and 1 for a miss.',
      'Your streak now counts only days you hit a daily XP goal. Pick Casual (50), Regular (100) or Serious (250) in Settings.',
      'Added a full-screen fire celebration the moment you hit your goal and extend your streak.',
      'Added streak freezes: miss a day and one is spent automatically to save your streak. You hold up to 2, and earn one back each week.',
      'Mastery is honest now — a word only advances when you get it right on its scheduled review, so cramming no longer “masters” it in one sitting, and a word counts as mastered only after it survives the full review ladder.',
      'Analytics now shows your level, daily XP against your goal, and packs completed instead of a raw attempt count.',
      'Added local reminders that nudge you to keep your streak (and let you know when a friend adds you), with a time you choose in Settings.',
      'Friend requests and acceptances now appear instantly, and a dot on the Friends tab flags new requests. Pull down to refresh the list.',
      'Redesigned friend comparison as a full screen with an XP line chart, both your avatars, and your shared streak lit between them.',
    ],
  },
  {
    version: '5.5.0',
    date: '2026-07-17',
    notes: [
      'Fixed haptic feedback, which never actually worked on Android — the app was asking the phone to vibrate without permission to do so, and the request was being silently ignored.',
      'Friends is now a tab, so it sits alongside Library, Dictionary, AI Coach and Analytics instead of being buried in the menu.',
      'Added friend streaks: practise on the same day as a friend to start one, and keep it alive by both practising before midnight.',
      'Added a Profile page where you can change your display name and pick an avatar.',
      'Added 12 avatars to choose from — your friends see yours next to your name.',
      'The header now shows your avatar instead of a settings gear; Settings moved inside Profile.',
      'The menu no longer repeats the tabs sitting right below it — it now has Profile, Settings, What’s new and Sign out.',
      'The tour now animates each feature as it introduces it, has a slide for Friends, and can be swiped through.',
      'A friend’s streak is now counted in your timezone rather than UTC, so it agrees with the streak on your own Analytics tab.',
    ],
  },
  {
    version: '5.0.0',
    date: '2026-07-17',
    notes: [
      'New app icon — an open book whose pages form a “V” — now used on the launcher, the splash screen, sign-in and both Word Smart book tiles.',
      'Flashcards no longer push “Again” and “Got it” off the screen when you flip a long card; the card scrolls instead and the buttons stay put.',
      'The app no longer redraws itself while you are reading — switching tabs, tapping the tab you are already on, and background sign-in refreshes all leave the page alone.',
      'The flashcard progress bar now slides forward between cards instead of restarting from zero each time.',
      'Synonyms now show as green pills and antonyms as red ones, in both Flashcards and the Dictionary.',
      'Added Friends: share your 6-digit code, connect with someone else’s, and compare streaks, mastery and accuracy.',
      'Added Revise: practise the words you learned longest ago, for a single pack or a whole book.',
      'The AI Coach now mixes in words you have not seen for a while, not only the ones you get wrong.',
      'You can now change your display name from Settings.',
      'The status bar now follows your light or dark theme.',
      'Deleting your account or signing in as someone else now clears your data straight away, without restarting the app.',
      'Smoother analytics: stats count up, the weekly chart rises into place, and cards fade in.',
    ],
  },
  {
    version: '4.0.0',
    date: '2026-07-15',
    notes: [
      'Refreshed the app with a new blue theme so the brand colour is no longer confused with the green “correct” colour.',
      'Redesigned the Word Smart 1 & 2 cards and gave each practice type its own large, centered tile.',
      'Flashcards now grow when you flip them, so the full definition, examples and synonyms fit without scrolling.',
      'The AI Coach now has its own tab next to Dictionary, and explains what it does the first time you open it.',
      'Rebuilt the Analytics dashboard with a weekly practice chart, a library-mastery bar and a best-streak stat.',
      'Sign-in now remembers your email when you tick “Remember me”, so you only need to type your password.',
      'Onboarding puts Back beside Next and shows Skip tour as a clear button.',
    ],
  },
  {
    version: '0.3.0',
    date: '2026-07-15',
    notes: [
      'Refreshed the whole look with a friendlier, higher-contrast colour system that is much easier to read in dark mode.',
      'Flashcards now show synonyms, antonyms and up to three example sentences on the back.',
      'Fixed matching practice so tapping the wrong meaning clearly flashes red instead of doing nothing.',
      'Sped up dictionary lookups and made them more reliable by using the free dictionary first, with Merriam-Webster for audio.',
      'Updates now download and install right inside the app instead of sending you to a web page.',
      'Cleaned up notes and example boxes with a softer, label-based style.',
    ],
  },
  {
    version: '0.2.2',
    date: '2026-07-15',
    notes: [
      'Fixed pronunciation audio and the AI coach, which were blocked from reaching the dictionary and AI services.',
      'Switched the whole app to the Google Sans Flex typeface for a cleaner, more consistent look.',
      'Centered the screen titles and lined the menu and settings icons up with them.',
      'Added a show/hide toggle to password fields so you can check what you typed.',
      'Added account deletion that also erases all of your data from the server.',
      'Added an in-app update check against GitHub releases, plus this changelog.',
    ],
  },
  {
    version: '0.2.1',
    date: '2026-07-14',
    notes: [
      'Added a password strength policy with live requirement checks while signing up.',
      'Fixed the authentication configuration and gave the app a new book icon.',
    ],
  },
  {
    version: '0.2.0',
    date: '2026-07-14',
    notes: [
      'Rebuilt the app on Vite, Tailwind, and vanilla JavaScript, wrapped for Android with Capacitor.',
    ],
  },
];
